#!/usr/bin/env node
/**
 * Offline license tooling. Keys are Ed25519: the private key stays with Plumbr,
 * the public key is embedded in the app (src/shared/license-pubkey.ts).
 *
 *   node scripts/license.mjs keygen                      # prints private key (keep!) and writes the public key file
 *   node scripts/license.mjs issue <name-or-email> [days] # prints a DRIFT-… key; days omitted = perpetual
 *
 * Private key comes from DRIFT_LICENSE_PRIVATE_KEY (base64 PKCS8 DER).
 */
import { generateKeyPairSync, sign, createPrivateKey } from 'node:crypto'
import { writeFileSync } from 'node:fs'

const [cmd, ...rest] = process.argv.slice(2)
const b64u = (b) => Buffer.from(b).toString('base64url')

if (cmd === 'keygen') {
  const { publicKey, privateKey } = generateKeyPairSync('ed25519')
  const pub = publicKey.export({ type: 'spki', format: 'der' }).toString('base64')
  const priv = privateKey.export({ type: 'pkcs8', format: 'der' }).toString('base64')
  writeFileSync(
    'src/shared/license-pubkey.ts',
    `/** Ed25519 public key (SPKI DER, base64). Generated by scripts/license.mjs keygen. */\nexport const LICENSE_PUBKEY = '${pub}'\n`
  )
  console.log('Wrote src/shared/license-pubkey.ts')
  console.log('\nDRIFT_LICENSE_PRIVATE_KEY (store in a password manager, never commit):\n' + priv)
} else if (cmd === 'issue') {
  const [name, days] = rest
  if (!name) throw new Error('usage: issue <name-or-email> [days]')
  if (days !== undefined && !(Number.isFinite(Number(days)) && Number(days) > 0))
    throw new Error(`days must be a positive number, got ${JSON.stringify(days)}`)
  const priv = process.env.DRIFT_LICENSE_PRIVATE_KEY
  if (!priv) throw new Error('DRIFT_LICENSE_PRIVATE_KEY not set')
  const payload = {
    n: name,
    i: Date.now(),
    e: days ? Date.now() + Number(days) * 86_400_000 : null
  }
  const data = Buffer.from(JSON.stringify(payload))
  const key = createPrivateKey({ key: Buffer.from(priv, 'base64'), format: 'der', type: 'pkcs8' })
  console.log(`DRIFT-${b64u(data)}.${b64u(sign(null, data, key))}`)
} else {
  console.log('usage: license.mjs keygen | issue <name> [days]')
  process.exit(2)
}
